import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  loader: { marginTop: 30 },
  roomItem: {
    flexDirection: "row",
    padding: 12,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#eee" },
  content: { flex: 1, marginLeft: 12 },
  header: { flexDirection: "row", justifyContent: "space-between" },
  name: { fontWeight: "600" },
  time: { color: "#999", fontSize: 12 },
  lastMessage: { color: "#666", marginTop: 4 },
  badge: {
    backgroundColor: "#ff3b30",
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeText: { color: "#fff", fontWeight: "600" },
  messageRow: {
    flexDirection: "row",
    marginVertical: 5,
    paddingHorizontal: 10,
  },
  myRow: { justifyContent: "flex-end" },
  otherRow: { justifyContent: "flex-start" },
  bubble: { maxWidth: "80%", padding: 10, borderRadius: 15 },
  myBubble: { backgroundColor: "#007AFF", borderBottomRightRadius: 2 },
  otherBubble: { backgroundColor: "#fff", borderBottomLeftRadius: 2 },
  messageText: { fontSize: 16 },
  myText: { color: "#fff" },
  otherText: { color: "#000" },
  inputContainer: {
    flexDirection: "row",
    padding: 10,
    backgroundColor: "#fff",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  input: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    maxHeight: 100,
  },
  sendButton: { padding: 5 },
});
